//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaPos.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public Nullable<int> ProductQuantityId { get; set; }
        public Nullable<double> OrderDetailQnty { get; set; }
        public Nullable<double> OrderDetailPrice { get; set; }
        public Nullable<double> OrderDetailDiscount { get; set; }
        public Nullable<bool> OrderDetailIsActive { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductQuantity ProductQuantity { get; set; }
    }
}
