//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaPos.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Void
    {
        public int VoidId { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public Nullable<System.TimeSpan> VoidTime { get; set; }
        public Nullable<bool> VoidAllOrder { get; set; }
        public Nullable<int> VoidReasonId { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual VoidReason VoidReason { get; set; }
    }
}
